### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by SphaeroX** [AuroBit/ComfyUI-OOTDiffusion#10]
I installed the plugin as described in the instructions and then added it to the custom nodes, unfortunately, I get an error:

```
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 8, in <module>
    from diffusers import AutoencoderKL, UniPCMultistepScheduler
ModuleNotFoundError: No module named 'diffusers'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: No module named 'diffusers'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion
```

**Comment by iyume** [comment]
pip install -r custom_nodes/ComfyUI-OOTDiffusion/requirements.txt

**Comment by SphaeroX** [comment]
going to C:\ComfyUI_windows_portable\ComfyUI>

Opened my shell

conda create -n ootd python=3.10
conda activate ootd

conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```
...
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(ootd) C:\ComfyUI_windows_portable\ComfyUI>
```

git clone https://github.com/AuroBit/ComfyUI-OOTDiffusion.git custom_nodes/ComfyUI-OOTDiffusion
```
...
(ootd) C:\ComfyUI_windows_portable\ComfyUI>git clone https://github.com/AuroBit/ComfyUI-OOTDiffusion.git custom_nodes/ComfyUI-OOTDiffusion
Cloning into 'custom_nodes/ComfyUI-OOTDiffusion'...
remote: Enumerating objects: 749, done.
remote: Counting objects: 100% (749/749), done.
remote: Compressing objects: 100% (606/606), done.
remote: Total 749 (delta 163), reused 726 (delta 140), pack-reused 0
Receiving objects: 100% (749/749), 4.56 MiB | 24.06 MiB/s, done.
Resolving deltas: 100% (163/163), done.
```

pip install -r custom_nodes/ComfyUI-OOTDiffusion/requirements.txt
```
Installing collected packages: pytz, pydub, ninja, ffmpy, zipp, websockets, tzdata, toolz, tomlkit, tifffile, sniffio, six, shellingham, semantic-version, scipy, safetensors, ruff, rpds-py, regex, python-multipart, pyparsing, pygments, pydantic-core, psutil, packaging, orjson, opencv-python, mdurl, lazy_loader, kiwisolver, importlib-resources, imageio, h11, fsspec, fonttools, exceptiongroup, einops, cycler, contourpy, colorama, attrs, annotated-types, aiofiles, tqdm, scikit-image, referencing, python-dateutil, pydantic, markdown-it-py, importlib-metadata, httpcore, click, anyio, uvicorn, typer, starlette, rich, pandas, matplotlib, jsonschema-specifications, huggingface-hub, httpx, tokenizers, jsonschema, gradio-client, fastapi, diffusers, accelerate, transformers, altair, gradio
Successfully installed accelerate-0.27.2 aiofiles-23.2.1 altair-5.2.0 annotated-types-0.6.0 anyio-4.3.0 attrs-23.2.0 click-8.1.7 colorama-0.4.6 contourpy-1.2.0 cycler-0.12.1 diffusers-0.24.0 einops-0.7.0 exceptiongroup-1.2.0 fastapi-0.110.0 ffmpy-0.3.2 fonttools-4.49.0 fsspec-2024.2.0 gradio-4.19.2 gradio-client-0.10.1 h11-0.14.0 httpcore-1.0.4 httpx-0.27.0 huggingface-hub-0.21.3 imageio-2.34.0 importlib-metadata-7.0.1 importlib-resources-6.1.2 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 kiwisolver-1.4.5 lazy_loader-0.3 markdown-it-py-3.0.0 matplotlib-3.8.3 mdurl-0.1.2 ninja-1.11.1.1 opencv-python-4.9.0.80 orjson-3.9.15 packaging-23.2 pandas-2.2.1 psutil-5.9.8 pydantic-2.6.3 pydantic-core-2.16.3 pydub-0.25.1 pygments-2.17.2 pyparsing-3.1.1 python-dateutil-2.9.0 python-multipart-0.0.9 pytz-2024.1 referencing-0.33.0 regex-2023.12.25 rich-13.7.1 rpds-py-0.18.0 ruff-0.3.0 safetensors-0.4.2 scikit-image-0.22.0 scipy-1.12.0 semantic-version-2.10.0 shellingham-1.5.4 six-1.16.0 sniffio-1.3.1 starlette-0.36.3 tifffile-2024.2.12 tokenizers-0.15.2 tomlkit-0.12.0 toolz-0.12.1 tqdm-4.66.2 transformers-4.38.2 typer-0.9.0 tzdata-2024.1 uvicorn-0.27.1 websockets-11.0.3 zipp-3.17.0

(ootd) C:\ComfyUI_windows_portable\ComfyUI>
```

python main.py --windows-standalone-build
```
(ootd) C:\ComfyUI_windows_portable\ComfyUI>python main.py --windows-standalone-build
Total VRAM 12282 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.samplers
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1, in <module>
    from .k_diffusion import sampling as k_diffusion_sampling
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 6, in <module>
    import torchsde
ModuleNotFoundError: No module named 'torchsde'
```

without env over the run_nvidia_gpu.bat
```
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12282 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 8, in <module>
    from diffusers import AutoencoderKL, UniPCMultistepScheduler
ModuleNotFoundError: No module named 'diffusers'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: No module named 'diffusers'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by iyume** [comment]
You are using custom conda virtual environment, so instead using the ComfyUI portable scripts (which use the packed env), use conda's python command directly.

> ModuleNotFoundError: No module named 'torchsde'

pip install -r requirements.txt  # located at ComfyUI root

**Comment by SphaeroX** [comment]
thanks that helped, now im stuck in the same issue like here: https://github.com/AuroBit/ComfyUI-OOTDiffusion/issues/8
