### ISSUE TITLE
DLL load failed while importing inplace_abn: 

### ISSUE THREAD

**Issue by SphaeroX** [AuroBit/ComfyUI-OOTDiffusion#11]
I've successfully installed the standard version of ComfyUI and activated my conda virtual environment. I've installed all the necessary requirements, including the one for Visual Studio Code. After running vcvars64.bat, I attempted to launch ComfyUI using my conda environment, but I encountered an error.

```
C:\ComfyUI>conda activate ootd

(ootd) C:\ComfyUI>python main.py
Total VRAM 12282 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
C:\Users\\miniconda3\envs\ootd\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\MGasc\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\MGasc\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\MGasc\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2132, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing inplace_abn: Das angegebene Modul wurde nicht gefunden.

Cannot import C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: DLL load failed while importing inplace_abn: Das angegebene Modul wurde nicht gefunden.

Import times for custom nodes:
  19.0 seconds (IMPORT FAILED): C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by iyume** [comment]
Run these command in your CMD (with conda activated) and paste the output:

```
set CUDA
where nvcc
```

**Comment by SphaeroX** [comment]
```
(ootd) C:\ComfyUI>set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
CUDA_PATH_V11_8=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8

(ootd) C:\ComfyUI>where nvcc
C:\Users\xxx\miniconda3\envs\ootd\bin\nvcc.exe
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe
```

**Comment by iyume** [comment]
try:

```
conda activate ootd
conda install cuda-toolkit=11.8 -c nvidia
set CUDA_HOME=%CONDA_PREFIX%
set CUDA_PATH=%CONDA_PREFIX%
python main.py
```

**Comment by SphaeroX** [comment]
installed but still the same error

```
C:\ComfyUI>conda activate ootd

(ootd) C:\ComfyUI>conda install cuda-toolkit=11.8 -c nvidia
Channels:
 - nvidia
 - defaults
 - pytorch
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\xxx\miniconda3\envs\ootd

  added / updated specs:
    - cuda-toolkit=11.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cuda-command-line-tools-12.1.1|                0           2 KB  nvidia
    cuda-compiler-12.3.2       |                0           2 KB  nvidia
    cuda-cuobjdump-12.3.101    |                0         3.8 MB  nvidia
    cuda-cuxxfilt-12.3.101     |                0         164 KB  nvidia
    cuda-documentation-12.3.101|                0          89 KB  nvidia
    cuda-nsight-compute-12.3.2 |                0           2 KB  nvidia
    cuda-nvdisasm-12.3.101     |                0        48.0 MB  nvidia
    cuda-nvml-dev-12.3.101     |                0          94 KB  nvidia
    cuda-nvprof-12.3.101       |                0         1.6 MB  nvidia
    cuda-nvprune-12.3.101      |                0         151 KB  nvidia
    cuda-nvvp-12.3.101         |                0       113.6 MB  nvidia
    cuda-sanitizer-api-12.3.101|                0        13.2 MB  nvidia
    cuda-toolkit-11.8.0        |                0           1 KB  nvidia
    cuda-tools-12.1.0          |                0           1 KB  nvidia
    cuda-visual-tools-12.1.0   |                0           1 KB  nvidia
    nsight-compute-2023.3.1.1  |                0       635.7 MB  nvidia
    ------------------------------------------------------------
                                           Total:       816.4 MB

The following NEW packages will be INSTALLED:

  cuda-command-line~ nvidia/win-64::cuda-command-line-tools-12.1.1-0
  cuda-compiler      nvidia/win-64::cuda-compiler-12.3.2-0
  cuda-cuobjdump     nvidia/win-64::cuda-cuobjdump-12.3.101-0
  cuda-cuxxfilt      nvidia/win-64::cuda-cuxxfilt-12.3.101-0
  cuda-documentation nvidia/win-64::cuda-documentation-12.3.101-0
  cuda-nsight-compu~ nvidia/win-64::cuda-nsight-compute-12.3.2-0
  cuda-nvdisasm      nvidia/win-64::cuda-nvdisasm-12.3.101-0
  cuda-nvml-dev      nvidia/win-64::cuda-nvml-dev-12.3.101-0
  cuda-nvprof        nvidia/win-64::cuda-nvprof-12.3.101-0
  cuda-nvprune       nvidia/win-64::cuda-nvprune-12.3.101-0
  cuda-nvvp          nvidia/win-64::cuda-nvvp-12.3.101-0
  cuda-sanitizer-api nvidia/win-64::cuda-sanitizer-api-12.3.101-0
  cuda-toolkit       nvidia/win-64::cuda-toolkit-11.8.0-0
  cuda-tools         nvidia/win-64::cuda-tools-12.1.0-0
  cuda-visual-tools  nvidia/win-64::cuda-visual-tools-12.1.0-0
  nsight-compute     nvidia/win-64::nsight-compute-2023.3.1.1-0

Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(ootd) C:\ComfyUI>set CUDA_HOME=%CONDA_PREFIX%

(ootd) C:\ComfyUI>set CUDA_PATH=%CONDA_PREFIX%

(ootd) C:\ComfyUI>python main.py
** ComfyUI startup time: 2024-03-02 09:04:20.810110
** Platform: Windows
** Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
** Python executable: C:\Users\xxx\miniconda3\envs\ootd\python.exe
** Log path: C:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.8.3)
### ComfyUI Revision: 2030 [cb7c3a29] | Released on '2024-02-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\image-resize-comfyui
   0.3 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds (IMPORT FAILED): C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

Starting server

To see the GUI go to: http://127.0.0.1:8188


```

**Comment by iyume** [comment]
Have you checkout the windows instruction in README? Have you setup the MSVC and activated the vcvars64.bat?

**Comment by SphaeroX** [comment]
yes i did, and tryed antoher time, i got the Visual Studio Community Edition 2022 but that shouldnt be a problem?
```
C:\Users\xxx>cd C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build>conda activate ootd

(ootd) C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build>vcvars64.bat
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.9.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

(ootd) C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build>cd C:\ComfyUI

(ootd) C:\ComfyUI>python main.py
** ComfyUI startup time: 2024-03-02 12:43:32.556592
** Platform: Windows
** Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
** Python executable: C:\Users\xxx\miniconda3\envs\ootd\python.exe
** Log path: C:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32472 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.8.3)
### ComfyUI Revision: 2030 [cb7c3a29] | Released on '2024-02-29'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\xxx\miniconda3\envs\ootd\lib\site-packages\torch\utils\cpp_extension.py", line 2132, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing inplace_abn: Das angegebene Modul wurde nicht gefunden.

Cannot import C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: DLL load failed while importing inplace_abn: Das angegebene Modul wurde nicht gefunden.
### Loading: Workspace Manager (V1.0.0)

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: C:\ComfyUI\custom_nodes\images-grid-comfy-plugin-main
   0.0 seconds: C:\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.3 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager
   1.2 seconds (IMPORT FAILED): C:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by iyume** [comment]
> try:
> 
> ```
> conda activate ootd
> conda install cuda-toolkit=11.8 -c nvidia
> set CUDA_HOME=%CONDA_PREFIX%
> set CUDA_PATH=%CONDA_PREFIX%
> python main.py
> ```

I didn't see you add these lines, add these command after you activate vcvars64.bat

**Comment by SphaeroX** [comment]
now it works, the hugginface cli dont work for me when im on ethernet, doesnt know why lol.... Heres a Step by Step Instrcution


---

Download and install Visual Studio from: https://visualstudio.microsoft.com/

Run the "Visual Studio Installer" and click on "Change" for your installation.

Under individual components, ensure to include:

- "msvc v143" (VS 2022 C++ x64/x86 build tools (latest version))
- CRT (Windows Universal C Runtime)
- "Windows 11 SDK" (or Windows 10 SDK, depending on your preference)

Install Conda and ensure to select the option to add Conda to your PATH variable during installation.

Create a new Conda environment with Python 3.10:
```bash
conda create -n ootd python=3.10
```

Activate the new environment:
```bash
conda activate ootd
```

Install PyTorch, torchvision, torchaudio, and specify the CUDA version compatible with your system:
```bash
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

Install CUDA NVCC and CUDA Toolkit:
```bash
conda install cuda-nvcc -c nvidia
conda install cuda-toolkit=11.8 -c nvidia
```

Navigate to your project folder (replace `C:\COMFYFOLDER` with your actual folder path):
```bash
cd C:\COMFYFOLDER
```

Clone the required repository into the specified directory:
```bash
git clone https://github.com/AuroBit/ComfyUI-OOTDiffusion.git custom_nodes/ComfyUI-OOTDiffusion
```


Install the required Python packages using `pip` and the provided requirements files:
```bash
pip install -r custom_nodes/ComfyUI-OOTDiffusion/requirements.txt
pip install -r requirements.txt
```

To set up your environment variables for Visual Studio build tools, navigate to the Visual Studio installation directory and run `vcvars64.bat`:
```bash
cd "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build"
vcvars64.bat
```

Return to your project folder and run the main Python script:
```bash
cd C:\COMFYFOLDER
python main.py
```

Ensure to replace paths and versions as necessary to match your system configuration and the specific versions you are using.

---

**Comment by iyume** [comment]
Good job.
