### ISSUE TITLE
pls advise

### ISSUE THREAD

**Issue by xiohulp** [AuroBit/ComfyUI-OOTDiffusion#12]
1. 每次启动COMFYUI，都要再次运行vcvars64.bat然后再启动comfy吗？我试了用启动器启动，但是 import failed
2. 说明中强调用prompt，但是配图确实powershell，能说明一下吗？

**Comment by iyume** [comment]
第一点：只有第一次启动编译的时候需要用到，后续都不需要，直接 conda activate 启动就行。
第二点：我用的是 CMD 麻烦你看清楚。

**Comment by xiohulp** [comment]
你好，感谢回复。没有冒犯的意思哈。
1. 我觉得也应该是运行一次就可以了，但是无论是cmd启动，还是用秋叶启动器启动，都报错了，跟之前一样的报错，是我这哪里配置的有问题吗？

Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "D:\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "D:\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.ext\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by iyume** [comment]
你的意思是，你编译一次后可以运行，启用着 vcvars64.bat 可以运行，但是你不希望每次启动都激活 vcvars64.bat 是吗？

**Comment by iyume** [comment]
理论上应该不需要每次激活，麻烦的话就写个脚本吧
