### ISSUE TITLE
[Windows] subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by usaking12** [AuroBit/ComfyUI-OOTDiffusion#2]
期待升级迭代解决win10报错问题和兼容问题
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/custom-node-list.json
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "E:\ComfyUI\en\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 5, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\en\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "E:\ComfyUI\en\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\ComfyUI\en\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "E:\ComfyUI\en\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "E:\ComfyUI\en\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\en\python_embeded\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\en\python_embeded\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import E:\ComfyUI\en\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by usaking12** [comment]
最好能升级环境python3.11+Torch2.1.2+cu12.1

**Comment by iyume** [comment]
这个好像是 torch cpp_extensions 在 windows 下需要配置 msvc 编译器。

你可以参照：https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/39#issuecomment-984003344

**Comment by iyume** [comment]
https://github.com/levihsu/OOTDiffusion/issues/11#issuecomment-1956179383

根据 OOTDiffusion 作者的说法，他也只在 linux 下测试过。

明天有空的话我尝试在 windows 下部署试试。

**Comment by usaking12** [comment]
在python3.11+Torch2.1.2+cu12.1环境下， 问题已经解决：  msvc 编译器。vs2022设置2个环境变量：LIB，INCLUDE。运行了vcvarsx86_amd64.bat 。运行正常了

**Comment by usaking12** [comment]
其他全身、裙子节点，辛苦大佬了。期待进一步更新。

**Comment by jesenzhang** [comment]
> 在python3.11+Torch2.1.2+cu12.1环境下， 问题已经解决： msvc 编译器。vs2022设置2个环境变量：LIB，INCLUDE。运行了vcvarsx86_amd64.bat 。运行正常了

能具体说一下吗，我也是这个环境，配置之后还是编译不过
![image](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/7984556/e61b6f39-b525-4743-939c-8d3b41cea12f)

**Comment by iyume** [comment]
https://github.com/AuroBit/ComfyUI-OOTDiffusion?tab=readme-ov-file#Windows-%E6%8C%87%E5%8D%97

Windows 指南已出

**Comment by iyume** [comment]
@jesenzhang

**Comment by jesenzhang** [comment]
> @jesenzhang

收到！
