### ISSUE TITLE
  (IMPORT FAILED): E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion

### ISSUE THREAD

**Issue by ellyoun13** [AuroBit/ComfyUI-OOTDiffusion#33]
![스크린샷 2024-03-28 185221](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/160593453/c7f56268-f3df-4752-80cb-c18f4c90ec10)

**Comment by iyume** [comment]
detail traceback pls

**Comment by ellyoun13** [comment]
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 23, in <module>
    from .pipelines_ootd.pipeline_ootd import OotdPipeline
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\pipeline_ootd.py", line 27, in <module>
    from .unet_vton_2d_condition import UNetVton2DConditionModel
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_condition.py", line 23, in <module>
    from .unet_vton_2d_blocks import (
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\unet_vton_2d_blocks.py", line 23, in <module>
    from .transformer_vton_2d import Transformer2DModel
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\pipelines_ootd\transformer_vton_2d.py", line 29, in <module>
    from diffusers.models.embeddings import CaptionProjection, PatchEmbed
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

**Comment by iyume** [comment]
try `git switch diffusers-0.26` under the `custom_nodes/ComfyUI-OOTDiffusion` directory

**Comment by Aljnk** [comment]
same problem - git switch diffusers-0.26 work! Thanks :)
