### ISSUE TITLE
大佬好，我把ComfyUI-OOTDiffusion放到AI绘世-comfyui的custom_nodes内，然后这个插件启动报错，加载不了

### ISSUE THREAD

**Issue by renruiw** [AuroBit/ComfyUI-OOTDiffusion#34]
Traceback (most recent call last):
 File "D:\sd-webui-aki-v4.1-original\comfyui\nodes.py", line 1888, in load_custom_node
  module_spec.loader.exec_module(module)
 File "<frozen importlib._bootstrap_external>", line 940, in exec_module
 File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
  from .inference_ootd import OOTDiffusion
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
  from .humanparsing.aigc_run_parsing import Parsing
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
  from .parsing_api import load_atr_model, load_lip_model, inference
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
  from . import networks
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
  from .AugmentCE2P import resnet101
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
  from ..modules import InPlaceABNSync
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
  from .bn import ABN, InPlaceABN, InPlaceABNSync
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
  from .functions import *
 File "D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
  _backend = load(name="inplace_abn",
        ^^^^^^^^^^^^^^^^^^^^^^^^
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
  return _jit_compile(
      ^^^^^^^^^^^^^
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
  _write_ninja_file_and_build_library(
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
  _write_ninja_file_to_build_library(
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
  _write_ninja_file(
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
  cl_paths = subprocess.check_output(['where',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\subprocess.py", line 466, in check_output
  return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "D:\sd-webui-aki-v4.1-original\comfyui\.ext\Lib\subprocess.py", line 571, in run
  raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import D:\sd-webui-aki-v4.1-original\comfyui\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.
这个问题怎么解决的好？我照着您的windows教程vcvas64.bat打开是可行的。我用绘世启动器直接打开就不行了。

**Comment by iyume** [comment]
你修改一下它的启动脚本，在脚本前激活。

如果你确定同一个环境编译完成可以启动，那么可以添加 cl 所在目录到环境变量，编译完成后它就只是一个没用的 check 确实很烦。

**Comment by renruiw** [comment]
我先cmd加载vcvars64.bat 然后再打开启动器就解决了。十分感谢回答
