### ISSUE TITLE
ModuleNotFoundError: No module named 'ComfyUI-OOTDiffusion-diffusers-0'

### ISSUE THREAD

**Issue by 6sixteen** [AuroBit/ComfyUI-OOTDiffusion#36]
I try to install  ComfyUI-OOTDiffusion-diffusers-0.26 and I follow the readme，but I meet the promblem

Traceback (most recent call last):
  File "C:\Z\Final ComfyUI\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Z\Final ComfyUI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion-diffusers-0.26\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\Z\Final ComfyUI\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion-diffusers-0.26\inference_ootd.py", line 16, in <module>
    from . import pipelines_ootd
ModuleNotFoundError: No module named 'ComfyUI-OOTDiffusion-diffusers-0'

**Comment by 6sixteen** [comment]
emmm
Although I don‘t know why，but i success 
When you clone ComfyUI-OOTDiffusion-diffusers-0.26，and just change the filename to ComfyUI-OOTDiffusion-diffusers-0
That's all !
