### ISSUE TITLE
Error occurred when executing LoadOOTDPipelineHub:

### ISSUE THREAD

**Issue by Cokeheart** [AuroBit/ComfyUI-OOTDiffusion#39]
![微信图片_20240413002329](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/124596170/1c3b4637-1551-405a-b1ea-f78101590204)
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025389F185B0>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/levihsu/OOTDiffusion/revision/d33c517dc1b0718ea1136533e3720bb08fae641b (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025389F185B0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\_snapshot_download.py", line 179, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\hf_api.py", line 2275, in repo_info
    return method(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\hf_api.py", line 2084, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/levihsu/OOTDiffusion/revision/d33c517dc1b0718ea1136533e3720bb08fae641b (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025389F185B0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 4979fbaa-f4ce-43f3-bfb8-de5b85fd4fe6)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 79, in load
    path = snapshot_download(
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\_snapshot_download.py", line 251, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

Prompt executed in 21.05 seconds

**Comment by iyume** [comment]
Check your internet connection.
