### ISSUE TITLE
Nodes failed to load in ComfyUI

### ISSUE THREAD

**Issue by new-to-here** [AuroBit/ComfyUI-OOTDiffusion#8]
![Screenshot 2024-02-28 195407](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/153484258/d5cd0fa4-058a-4c2e-b1be-724f0c134ebb)
![Screenshot 2024-02-28 195644](https://github.com/AuroBit/ComfyUI-OOTDiffusion/assets/153484258/b8c634ee-fc53-4c86-9d81-aca1c7ee8ef0)

I tried Both Installation method in Windows machine, 
1. Installing via Manager.
2. Installing by Git Instruction. ( As it said to in install in OOTD environment )

both throw this error, Can anyone assist me to overcome this error

**Comment by iyume** [comment]
Can you provide the exception traceback which shows on the terminal?

**Comment by new-to-here** [comment]
THIS ARE THE CMD STATUS

  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s).
**Traceback (most recent call last):**
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\__init__.py", line 10, in <module>
    from .inference_ootd import OOTDiffusion
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\inference_ootd.py", line 17, in <module>
    from .humanparsing.aigc_run_parsing import Parsing
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\aigc_run_parsing.py", line 1, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\parsing_api.py", line 7, in <module>
    from . import networks
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\__init__.py", line 2, in <module>
    from .AugmentCE2P import resnet101
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from ..modules import InPlaceABNSync
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2238, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2373, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import C:\Jarvis\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by iyume** [comment]
Follow the instruction of https://github.com/AuroBit/ComfyUI-OOTDiffusion#windows-%E6%8C%87%E5%8D%97 to setup on windows.
